exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

collections:
  anouncements:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "news/_posts"
      type: "posts"
    values:
      category: "news"
  - scope:
      path: "anouncements/_posts"
      type: "posts"
    values:
      category: "anouncements"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

gems:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 10
  title: ":title"
  permalink: "/page:num/"
  trail:
    before: 10
    after: 10
